#!/usr/bin/env /bin/sh
# Generated by Volcano from hello-world.vol

set -o posix
set -e

#  Volcano shell assembly operations.
#

# Arithmetic operators
#
add() {
    echo $(($1 + $2))
}

sub() {
    echo $(($1 - $2))
}

div() {
    if [ "$2" -ne 0 ]; then
        echo $(($1 / $2))
    else
        echo "Error: Division by zero" >&2
        exit 1
    fi
}

mul() {
    echo $(($1 * $2))
}
# The Volcano runtime library.
#
LOG_FILE=$(mktemp)

tail -f "$LOG_FILE" &

print () {
    echo "$1" >> "$LOG_FILE"
}

input () {
    read -r -p "$1" RESULT >> "$LOG_FILE"
}

array_append () {

    local array="$1"
    local val="$2"

    set -- "$array"
    set -- "$@" "$val"
    
    RESULT="$*"
}

# End of Volcano runtime library.
#
hello_world_hello () {
    RESULT=
    local name=${1:-}
    print "Hello $name!"
 }

hello_world_hello "World"
